### PR TITLE
get_device_meta() tango service

### PR DESCRIPTION
**Pull request by abhijith0505**

### CODE REVIEW

**Comment by abhijith0505** [comment]
@mtambos  This is the latest PR
I had to start a new PR as I had messed up the repo on my end. Had to start fresh
Sorry about that

**Comment by mtambos** [comment]
you could just clone the repository again, unless the other PR was
corrupted somehow, there's no need for a new one

**Comment by abhijith0505** [comment]
that's what i did, but there were lots of conflicts suddenly so I decided to have a fresh PR.
I shall be cautious from the next time.
Thanks

**Comment by mtambos** [comment]
What do you mean? There cannot be conflicts in a fresh clone.
Was the PR that I've already merged correct or was it corrupted?

**Comment by abhijith0505** [comment]
There were conflicts, hence I did a fresh clone.
And yes, the merged PR was the old, in-complete version.
This PR is the one that needs to be merged.

Sorry for the confusion.

**Pull request merged**
